### ISSUE TITLE
Integration Local Storage

### ISSUE THREAD

**Issue by fess986** [fess986/cinema-js-native-adv-lvl#61]
Integration Local Storage to work in offline mode with project:
- [x]  Add Local Store class in project #62 
- [x]  Add Provider class in project #63 
- [x]  Add store class methods #64 
- [x]  Provider class - update method #65 
- [x]   Provider class - remove comment method #66 
- [x]  Provider class - create comment method #67 
- [x]  Synchronization with server #68

**Comment by fess986** [comment]
all tasks completed
