### ISSUE TITLE
Add service worker  in project

### ISSUE THREAD

**Issue by fess986** [fess986/cinema-js-native-adv-lvl#79]
Add service worker  to get ability start project in offline mode by cashing static resorses

- [x]  Registrer Service Worker #75 
- [x]  Install Service Worker #76 
- [x]  Activate Service Worker #77 
- [x]  Use Service Worker for interception fetch requests #78

**Comment by fess986** [comment]
all tasks are closed
